---
title: "fDOM meteorology regression forecasts"
author: "Dexter Howard"
date: "2024-08-27"
output: html_document
---


## Load packages and functions 

```{r}
library(tidyverse)

source('./Functions/MetRegression_4cast_function.R')

```


## Get data 

target data 
```{r}
### Read in df 
targets_fdom <- read_csv("../Data/GeneratedData/Targets_fDOM_allReservoirs.csv")

### FCR water Q data
fcr_waterQ <- targets_fdom |>
  filter(site_id == "fcre")

###BVR water Q data
bvr_waterQ <- targets_fdom |>
  filter(site_id == "bvre")

### CCR water Q data
ccr_waterQ <- targets_fdom |>
  filter(site_id == "ccre")

```


NOAA forecasts 
```{r}
## FCR and BVR 
fcr_bvr_noaa_daily <- read.csv("../Data/GeneratedData/FCR_NOAA_stage2_dailyaverage_27sep20-12aug24.csv")

## CCR
ccr_noaa_daily <- read.csv("../Data/GeneratedData/CCR_NOAA_stage2_dailyaverage_29sep20-12aug24.csv")

```


Set up directories to hold forecasts

```{r}
##uncomment if folders don't exist
# dir.create("../Data/Forecast_Outputs/MetRegress_4casts")
# dir.create("../Data/Forecast_Outputs/MetRegress_4casts/fcre")
# dir.create("../Data/Forecast_Outputs/MetRegress_4casts/bvre")
# dir.create("../Data/Forecast_Outputs/MetRegress_4casts/ccre")

```




## Run Met Regression forecasts 

FCR
```{r}
##set up function inputs
forecast_date <- seq(ymd("2023-04-13"), ymd("2024-08-11"), by = "day")

model_id <- "fDOM_MetRegression_dwh"
var <- "fDOM_QSU_mean"
site <- "fcre"
forecast_depths <- 1.6
project_id <- "vera4cast"
n_members <- 31
forecast_horizon <- 16

calibration_start_date <- ymd("2023-03-13") #ymd("2020-09-27") #going back to start of noaa4casts since we're not limited by FLARE output

targets_df <- fcr_waterQ
noaa_4cast <- fcr_bvr_noaa_daily

output_folder <- paste0((str_sub(getwd(), end = -8)), "Data/Forecast_Outputs/MetRegress_4casts/fcre/", model_id, "_", site, "_")


#run forecasts

for (j in 1:length(forecast_date)) {
  
  print(forecast_date[j]) 
  
generate_fDOM_regress_forecast(forecast_date = forecast_date[j], forecast_horizon = forecast_horizon, 
                               n_members = n_members, output_folder = output_folder, model_id = model_id, 
                               targets_df = targets_df,
                       noaa_4cast = noaa_4cast, var = var,site = site, forecast_depths = forecast_depths,
                       project_id = project_id,
                      calibration_start_date = calibration_start_date )

      } #end function


## Notes on for loop: breaks 12aug24 - end of NOAA data


```



BVR
```{r}
##set up function inputs
forecast_date <- seq(ymd("2023-04-13"), ymd("2024-08-11"), by = "day")

model_id <- "fDOM_MetRegression_dwh"
var <- "fDOM_QSU_mean"
site <- "bvre"
forecast_depths <- 1.5
project_id <- "vera4cast"
n_members <- 31
forecast_horizon <- 16

calibration_start_date <- ymd("2023-03-13") #ymd("2020-09-27") #going back to start of noaa4casts since we're not limited by FLARE output

targets_df <- bvr_waterQ
noaa_4cast <- fcr_bvr_noaa_daily

output_folder <- paste0((str_sub(getwd(), end = -8)), "Data/Forecast_Outputs/MetRegress_4casts/bvre/", model_id, "_", site, "_")


#run forecasts

for (j in 1:length(forecast_date)) {
  
  print(forecast_date[j]) 
  
generate_fDOM_regress_forecast(forecast_date = forecast_date[j], forecast_horizon = forecast_horizon, 
                               n_members = n_members, output_folder = output_folder, model_id = model_id, 
                               targets_df = targets_df,
                       noaa_4cast = noaa_4cast, var = var,site = site, forecast_depths = forecast_depths,
                       project_id = project_id,
                      calibration_start_date = calibration_start_date )

      } #end function


## Notes on for loop: breaks 12aug24 - end of NOAA data


```


CCR
```{r}
##set up function inputs
forecast_date <- seq(ymd("2023-04-13"), ymd("2024-08-11"), by = "day")

model_id <- "fDOM_MetRegression_dwh"
var <- "fDOM_QSU_mean"
site <- "ccre"
forecast_depths <- 1.5
project_id <- "vera4cast"
n_members <- 31
forecast_horizon <- 16

calibration_start_date <- ymd("2023-03-13") #ymd("2020-09-27") #going back to start of noaa4casts since we're not limited by FLARE output

targets_df <- ccr_waterQ
noaa_4cast <- ccr_noaa_daily

output_folder <- paste0((str_sub(getwd(), end = -8)), "Data/Forecast_Outputs/MetRegress_4casts/ccre/", model_id, "_", site, "_")


#run forecasts

for (j in 1:length(forecast_date)) {
  
  print(forecast_date[j]) 
  
generate_fDOM_regress_forecast(forecast_date = forecast_date[j], forecast_horizon = forecast_horizon, 
                               n_members = n_members, output_folder = output_folder, model_id = model_id, 
                               targets_df = targets_df,
                       noaa_4cast = noaa_4cast, var = var,site = site, forecast_depths = forecast_depths,
                       project_id = project_id,
                      calibration_start_date = calibration_start_date )

      } #end function


## Notes on for loop: breaks 12aug24 - end of NOAA data


```







