---
title: "fDOM_Climatology_forecast_generation"
author: "Dexter Howard"
date: "2024-06-28"
output: html_document
---


## Load packages and functions 

```{r}
library(tidyverse)

source('./Functions/Climatology_4cast_function.R')

```


## Get data 

target data 
```{r}
### Read in df 
targets_fdom <- read_csv("../Data/GeneratedData/Targets_fDOM_allReservoirs.csv") %>% 
  filter(datetime >= ymd("2021-07-01")) #to line up w/ start of CCR EXO deployement so all reservoirs have same training
  #filter(datetime >= ymd("2023-03-13")) #to line up w/ other models

### FCR water Q data
fcr_waterQ <- targets_fdom |>
  filter(site_id == "fcre")

###BVR water Q data
bvr_waterQ <- targets_fdom |>
  filter(site_id == "bvre")

### CCR water Q data
ccr_waterQ <- targets_fdom |>
  filter(site_id == "ccre")


```


Set up directories to hold forecasts

```{r}
##uncomment if folders don't exist locally
# dir.create("../Data/Forecast_Outputs/Clim_4casts")
# dir.create("../Data/Forecast_Outputs/Clim_4casts/fcre")
# dir.create("../Data/Forecast_Outputs/Clim_4casts/bvre")
# dir.create("../Data/Forecast_Outputs/Clim_4casts/ccre")

```


## Run Climatology forecasts for all reservoirs

FCR
```{r}
## set up dates for for loop
forecast_date <- seq(ymd("2023-06-01"), ymd("2025-01-01"), by = "day")

##set up inputs to function
model_id <- "climatology"
var <- "fDOM_QSU_mean"
site <- "fcre"
depth <- 1.6
h <- 35

targets_df <- fcr_waterQ

output_folder <- paste0((str_sub(getwd(), end = -8)), "Data/Forecast_Outputs/Clim_4casts/fcre/", model_id, "_", site, "_")


#### FCR forecast loop

for (j in 1:length(forecast_date)) {
  
  print(forecast_date[j]) 
  
  generate_baseline_climatology(forecast_date = forecast_date[j],
                                targets = targets_df, h = h, site = site, model_id = model_id,
                                       var = var, depth = depth, 
                                       output_folder = output_folder)
          }

## NOTES

```



BVR
```{r}
## set up dates for for loop
forecast_date <- seq(ymd("2023-06-01"), ymd("2025-01-01"), by = "day")

##set up inputs to function
model_id <- "climatology"
var <- "fDOM_QSU_mean"
site <- "bvre"
depth <- 1.5
h <- 35

targets_df <- bvr_waterQ

output_folder <- paste0((str_sub(getwd(), end = -8)), "Data/Forecast_Outputs/Clim_4casts/bvre/", model_id, "_", site, "_")


#### BVR forecast loop

for (j in 1:length(forecast_date)) {
  
  print(forecast_date[j]) 
  
  generate_baseline_climatology(forecast_date = forecast_date[j],
                                targets = targets_df, h = h, site = site, model_id = model_id,
                                       var = var, depth = depth, 
                                       output_folder = output_folder)
          }

## NOTES

```



CCR
```{r}
## set up dates for for loop
forecast_date <- seq(ymd("2023-06-01"), ymd("2025-01-01"), by = "day")

##set up inputs to function
model_id <- "climatology"
var <- "fDOM_QSU_mean"
site <- "ccre"
depth <- 1.5
h <- 35

targets_df <- ccr_waterQ

output_folder <- paste0((str_sub(getwd(), end = -8)), "Data/Forecast_Outputs/Clim_4casts/ccre/", model_id, "_", site, "_")


#### CCR forecast loop

for (j in 1:length(forecast_date)) {
  
  print(forecast_date[j]) 
  
  generate_baseline_climatology(forecast_date = forecast_date[j],
                                targets = targets_df, h = h, site = site, model_id = model_id,
                                       var = var, depth = depth, 
                                       output_folder = output_folder)
          }

## NOTES

```








