---
title: "fDOM_Persistence_forecast_generation"
author: "Dexter Howard"
date: "2024-06-28"
output: html_document
---


## Load packages and functions 

```{r}
library(tidyverse)

source('./Functions/Persistence_4cast_function.R')

```


## Get data 

target data 
```{r}
### Read in df 
targets_fdom <- read_csv("../Data/GeneratedData/Targets_fDOM_allReservoirs.csv")

### FCR water Q data
fcr_waterQ <- targets_fdom |>
  filter(site_id == "fcre")

###BVR water Q data
bvr_waterQ <- targets_fdom |>
  filter(site_id == "bvre")

### CCR water Q data
ccr_waterQ <- targets_fdom |>
  filter(site_id == "ccre")

```


Set up directories to hold forecasts

```{r}
##uncomment if folders don't exist locally
# dir.create("../Data/Forecast_Outputs/Persist_4casts")
# dir.create("../Data/Forecast_Outputs/Persist_4casts/fcre")
# dir.create("../Data/Forecast_Outputs/Persist_4casts/bvre")
# dir.create("../Data/Forecast_Outputs/Persist_4casts/ccre")

```


## Run Climatology forecasts for all reservoirs

FCR
```{r}
## set up dates for for loop
#start at 12dec22, so we have a month of calibration for first forecast and go to end of data set 
forecast_date <- seq(ymd("2022-12-12"), ymd("2024-08-11"), by = "day")

##set up inputs to function
model_id <- "fable_persistence"
var <- "fDOM_QSU_mean"
site <- "fcre"
depth <- 1.6
h <- 17

targets_df <- fcr_waterQ

output_folder <- paste0((str_sub(getwd(), end = -8)), "Data/Forecast_Outputs/Persist_4casts/fcre/", model_id, "_", site, "_")


#### FCR forecast loop

for (j in 1:length(forecast_date)) {
  
  print(forecast_date[j]) 
  
  generate_baseline_persistenceRW(targets = targets_df, site = site, var = var, 
                                  forecast_date = forecast_date[j], model_id = model_id, 
                                  h = h, depth = depth, bootstrap = F, 
                                  output_folder = output_folder)
              } #end loop

## NOTES

```



BVR

```{r}
## set up dates for for loop
#start at 12dec22, so we have a month of calibration for first forecast and go to end of data set 
forecast_date <- seq(ymd("2022-12-12"), ymd("2024-08-11"), by = "day")

##set up inputs to function
model_id <- "fable_persistence"
var <- "fDOM_QSU_mean"
site <- "bvre"
depth <- 1.5
h <- 17

targets_df <- bvr_waterQ

output_folder <- paste0((str_sub(getwd(), end = -8)), "Data/Forecast_Outputs/Persist_4casts/bvre/", model_id, "_", site, "_")


#### BVR forecast loop

for (j in 1:length(forecast_date)) {
  
  print(forecast_date[j]) 
  
  generate_baseline_persistenceRW(targets = targets_df, site = site, var = var, 
                                  forecast_date = forecast_date[j], model_id = model_id, 
                                  h = h, depth = depth, bootstrap = F, 
                                  output_folder = output_folder)
              } #end loop

## NOTES

```




CCR

```{r}
## set up dates for for loop
#start at 12dec22, so we have a month of calibration for first forecast and go to end of data set 
forecast_date <- seq(ymd("2022-12-12"), ymd("2024-08-11"), by = "day")

##set up inputs to function
model_id <- "fable_persistence"
var <- "fDOM_QSU_mean"
site <- "ccre"
depth <- 1.5
h <- 17

targets_df <- ccr_waterQ

output_folder <- paste0((str_sub(getwd(), end = -8)), "Data/Forecast_Outputs/Persist_4casts/ccre/", model_id, "_", site, "_")


#### CCR forecast loop

for (j in 1:length(forecast_date)) {
  
  print(forecast_date[j]) 
  
  generate_baseline_persistenceRW(targets = targets_df, site = site, var = var, 
                                  forecast_date = forecast_date[j], model_id = model_id, 
                                  h = h, depth = depth, bootstrap = F, 
                                  output_folder = output_folder)
              } #end loop

## NOTES

```







