---
title: "Analyze fDOM hindcasts"
author: "Dexter Howard"
date: "2024-09-01"
output: html_document
---


```{r, message = F}
library(tidyverse)
library(score4cast)

```



## get targets data

```{r}
### S3 links 
targets_url <- "https://renc.osn.xsede.org/bio230121-bucket01/vera4cast/targets/project_id=vera4cast/duration=P1D/daily-insitu-targets.csv.gz"

### FCR water Q data
fcr_waterQ <- readr::read_csv(targets_url, show_col_types = FALSE) |>
  filter( site_id == "fcre",
         depth_m == 1.6,
         variable %in% c("fDOM_QSU_mean"))

###BVR water Q data
bvr_waterQ <- readr::read_csv(targets_url, show_col_types = FALSE) |>
  filter( site_id == "bvre",
         depth_m == 1.5,
         variable %in% c("fDOM_QSU_mean"))


### CCR water Q data
ccr_L1 <- read_csv("https://raw.githubusercontent.com/FLARE-forecast/CCRE-data/ccre-dam-data-qaqc/ccre-waterquality_L1.csv")
ccr_edi <- read_csv("https://pasta.lternet.edu/package/data/eml/edi/1069/2/ea78dd541e089687af1f4c4b550bc9ca" )
ccrfull <- rbind(ccr_edi, ccr_L1)

ccr_waterQ <- ccrfull |> 
  mutate(Date = as.Date(DateTime)) |> 
  group_by(Date) |> 
  summarise(fDOM_QSU_mean = mean(EXOfDOM_QSU_1, na.rm = T)) |> 
  mutate(site_id = "ccre",
         depth_m = 1.5) |> 
  select(Date, site_id, depth_m, fDOM_QSU_mean) |> 
  pivot_longer(-c(1:3), names_to = "variable", values_to = "observation") |> 
  rename(datetime = Date) |> mutate(project_id = "vera4cast", duration = "P1D")

#bind all three together for scoring later
allres_targets <- rbind(fcr_waterQ, bvr_waterQ, ccr_waterQ) 


```

## Compile AR 4cast outputs  

```{r}
#FCR AR forecasts
#bind forecast outputs into one data frame 
fcr_AR_output_all <- list.files(path = "../Data/Forecast_Outputs/AR_4casts/fcre", pattern = "*.csv", full.names = T) |> 
  base::lapply(read_csv) |> 
  bind_rows()  


#BVR AR forecasts
#bind forecast outputs into one data frame 
bvr_AR_output_all <- list.files(path = "../Data/Forecast_Outputs/AR_4casts/bvre", pattern = "*.csv", full.names = T) |> 
  base::lapply(read_csv) |> 
  bind_rows()  


#CCR AR forecasts
#bind forecast outputs into one data frame 
ccr_AR_output_all <- list.files(path = "../Data/Forecast_Outputs/AR_4casts/ccre", pattern = "*.csv", full.names = T) |> 
  base::lapply(read_csv) |> 
  bind_rows()  


#Compile AR forecasts and write csv
allres_AR <- rbind(fcr_AR_output_all, bvr_AR_output_all, ccr_AR_output_all)

write.csv(allres_AR, "../Data/Forecast_Outputs/AR_4casts/allReservoir_AR_4cast.csv", row.names = F)


```



### Compile NNETAR 4cast outputs  

All reservoir NNETAR forecasts
```{r}
#bind forecast outputs into one data frame 
allRes_NNETAR_output_all <- list.files(path = "../Data/Forecast_Outputs/NNETAR_4casts/allRes", pattern = "*.csv", full.names = T) |> 
  base::lapply(read_csv) |> 
  bind_rows()  

head(allRes_NNETAR_output_all)

#write csv of all data together
write.csv(allRes_NNETAR_output_all, "../Data/Forecast_Outputs/NNETAR_4casts/allReservoir_NNETAR_4cast.csv", row.names = F)


```



## Compile Climatology 4cast outputs  

```{r}
#FCR Clim forecasts
#bind forecast outputs into one data frame 
fcr_Clim_output_all <- list.files(path = "../Data/Forecast_Outputs/Clim_4casts/fcre", pattern = "*.csv", full.names = T) |> 
  base::lapply(read_csv) |> 
  bind_rows()  


#BVR Clim forecasts
#bind forecast outputs into one data frame 
bvr_Clim_output_all <- list.files(path = "../Data/Forecast_Outputs/Clim_4casts/bvre", pattern = "*.csv", full.names = T) |> 
  base::lapply(read_csv) |> 
  bind_rows()  


#CCR Clim forecasts
#bind forecast outputs into one data frame 
ccr_Clim_output_all <- list.files(path = "../Data/Forecast_Outputs/Clim_4casts/ccre", pattern = "*.csv", full.names = T) |> 
  base::lapply(read_csv) |> 
  bind_rows()  


#Compile Clim forecasts and write csv
allres_Clim <- rbind(fcr_Clim_output_all, bvr_Clim_output_all, ccr_Clim_output_all)

write.csv(allres_Clim, "../Data/Forecast_Outputs/Clim_4casts/allReservoir_Clim_4cast.csv", row.names = F)


```



## Compile Persistence 4cast outputs  

```{r}
#FCR Persist forecasts
#bind forecast outputs into one data frame 
fcr_Persist_output_all <- list.files(path = "../Data/Forecast_Outputs/Persist_4casts/fcre", pattern = "*.csv", full.names = T) |> 
  base::lapply(read_csv) |> 
  bind_rows()  


#BVR Persist forecasts
#bind forecast outputs into one data frame 
bvr_Persist_output_all <- list.files(path = "../Data/Forecast_Outputs/Persist_4casts/bvre", pattern = "*.csv", full.names = T) |> 
  base::lapply(read_csv) |> 
  bind_rows()  


#CCR Persist forecasts
#bind forecast outputs into one data frame 
ccr_Persist_output_all <- list.files(path = "../Data/Forecast_Outputs/Persist_4casts/ccre", pattern = "*.csv", full.names = T) |> 
  base::lapply(read_csv) |> 
  bind_rows()  


#Compile Persist forecasts and write csv
allres_Persist <- rbind(fcr_Persist_output_all, bvr_Persist_output_all, ccr_Persist_output_all)

write.csv(allres_Persist, "../Data/Forecast_Outputs/Persist_4casts/allReservoir_Persist_4cast.csv", row.names = F)

```



## Compile RainLag 4cast outputs  

```{r}
#FCR RainLab forecasts
#bind forecast outputs into one data frame 
fcr_RainLag_output_all <- list.files(path = "../Data/Forecast_Outputs/RainLag_4casts/fcre", pattern = "*.csv", full.names = T) |> 
  base::lapply(read_csv) |> 
  bind_rows()  


#BVR RainLab forecasts
#bind forecast outputs into one data frame 
bvr_RainLag_output_all <- list.files(path = "../Data/Forecast_Outputs/RainLag_4casts/bvre", pattern = "*.csv", full.names = T) |> 
  base::lapply(read_csv) |> 
  bind_rows()  


#CCR RainLab forecasts
#bind forecast outputs into one data frame 
ccr_RainLag_output_all <- list.files(path = "../Data/Forecast_Outputs/RainLag_4casts/ccre", pattern = "*.csv", full.names = T) |> 
  base::lapply(read_csv) |> 
  bind_rows()  

#Compile RainLag forecasts and write csv
allres_RainLag <- rbind(fcr_RainLag_output_all, bvr_RainLag_output_all, ccr_RainLag_output_all)

write.csv(allres_RainLag, "../Data/Forecast_Outputs/RainLag_4casts/allReservoir_RainLag_4cast.csv", row.names = F)

```



## Compile Meteo Regression 4cast outputs  

```{r}
#FCR MetRegress forecasts
#bind forecast outputs into one data frame 
fcr_MetRegress_output_all <- list.files(path = "../Data/Forecast_Outputs/MetRegress_4casts/fcre", pattern = "*.csv", full.names = T) |> 
  base::lapply(read_csv) |> 
  bind_rows()  


#BVR MetRegress forecasts
#bind forecast outputs into one data frame 
bvr_MetRegress_output_all <- list.files(path = "../Data/Forecast_Outputs/MetRegress_4casts/bvre", pattern = "*.csv", full.names = T) |> 
  base::lapply(read_csv) |> 
  bind_rows()


#CCR MetRegress forecasts
#bind forecast outputs into one data frame 
ccr_MetRegress_output_all <- list.files(path = "../Data/Forecast_Outputs/MetRegress_4casts/ccre", pattern = "*.csv", full.names = T) |> 
  base::lapply(read_csv) |> 
  bind_rows()


#Compile MetRegress forecasts and write csv
allres_MetRegress <- rbind(fcr_MetRegress_output_all, bvr_MetRegress_output_all, ccr_MetRegress_output_all)

write.csv(allres_MetRegress, "../Data/Forecast_Outputs/MetRegress_4casts/allReservoir_MetRegress_4cast.csv", row.names = F)


```


## Scoring forecast 
using score4cast to get crps

```{r}
## AR scores 
AR_scores <- crps_logs_score(allres_AR, allres_targets)

write.csv(AR_scores, "../Data/Forecast_Outputs/AR_4casts/allReservoir_AR_4cast_Scores.csv", row.names = F)

## RainLag scores 
RainLag_scores <- crps_logs_score(allres_RainLag, allres_targets)

write.csv(RainLag_scores, "../Data/Forecast_Outputs/RainLag_4casts/allReservoir_RainLag_4cast_Scores.csv", row.names = F)

## MetRegress scores 
MetRegress_scores <- crps_logs_score(allres_MetRegress, allres_targets)

write.csv(MetRegress_scores, "../Data/Forecast_Outputs/MetRegress_4casts/allReservoir_MetRegress_4cast_Scores.csv", row.names = F)

## nnetar scores 
nnetar_scores <- crps_logs_score(allRes_NNETAR_output_all, allres_targets)

write.csv(nnetar_scores, "../Data/Forecast_Outputs/NNETAR_4casts/allReservoir_NNETAR_4cast_Scores.csv", row.names = F)


## Clim scores 
Clim_scores <- crps_logs_score(allres_Clim, allres_targets)

write.csv(Clim_scores, "../Data/Forecast_Outputs/Clim_4casts/allReservoir_Clim_4cast_Scores.csv", row.names = F)

## Persist scores 
Persist_scores <- crps_logs_score(allres_Persist, allres_targets)

write.csv(Persist_scores, "../Data/Forecast_Outputs/Persist_4casts/allReservoir_Persist_4cast_Scores.csv", row.names = F)


```

Bind all scores together and write csv

```{r}
##Bind scores together 
All_Scores <- rbind(AR_scores, RainLag_scores, MetRegress_scores, nnetar_scores, Clim_scores, Persist_scores) |> 
  mutate(model_id = ifelse(model_id %in% c("example_fDOM_AR_dwh", "fDOM_AR_dwh"), "fDOM_AR_dwh", model_id)
         ) #fix different model_id names for AR models (remove example)

write.csv(All_Scores, "../Data/allReservoir_allmodel_4cast_Scores.csv", row.names = F)

```


