---
title: "fDOM_NNETAR_forecast_generation"
author: "Dexter Howard"
date: "2024-08-23"
output: html_document
---


## Load packages and functions 

```{r}
library(tidyverse)

source('./Functions/NNETAR_4cast_function.R')

```


## Get data 

target data 
```{r}
### S3 links 
targets_url <- "https://renc.osn.xsede.org/bio230121-bucket01/vera4cast/targets/project_id=vera4cast/duration=P1D/daily-insitu-targets.csv.gz"

ltreb_targets <- read_csv(targets_url) |> select(-project_id, -duration) |> 
  filter(variable == "fDOM_QSU_mean")


### CCR water Q data
ccr_L1 <- read_csv("https://raw.githubusercontent.com/FLARE-forecast/CCRE-data/ccre-dam-data-qaqc/ccre-waterquality_L1.csv")
ccr_edi <- read_csv("https://pasta.lternet.edu/package/data/eml/edi/1069/2/ea78dd541e089687af1f4c4b550bc9ca" )
ccrfull <- rbind(ccr_edi, ccr_L1)

ccr_targets <- ccrfull |> 
  mutate(Date = as.Date(DateTime)) |> 
  group_by(Date) |> 
  summarise(fDOM_QSU_mean = mean(EXOfDOM_QSU_1, na.rm = T)) |> 
  mutate(site_id = "ccre",
         depth_m = 1.5) |> 
  select(Date, site_id, depth_m, fDOM_QSU_mean) |> 
  pivot_longer(-c(1:3), names_to = "variable", values_to = "observation") |> 
  rename(datetime = Date)


##put all data together 
res_fdom <- rbind(ltreb_targets, ccr_targets)

#remove unneeded variables after getting data together
rm(ccr_edi, ccr_L1, ccr_targets, ccrfull, ltreb_targets, targets_url)


```



Set up directories to hold forecasts

```{r}
##uncomment lines below if folder don't exist
# dir.create("../Data/NNETAR_4casts")
# dir.create("../Data/NNETAR_4casts/allRes")

```


## Run NNETAR forecasts for all reservoir


```{r}

forecast_date <- seq(ymd("2022-12-12"), ymd("2024-08-26"), by = "day") #ymd("2022-12-12), ymd("2024-08-26")

var <- "fDOM_QSU_mean"
targets_df <- res_fdom
forecast_horizon <- 16

output_folder <- paste0((str_sub(getwd(), end = -8)), "Data/NNETAR_4casts/allRes/", "NNETAR_allRes_")


for (j in 1:length(forecast_date)) {
  
  print(forecast_date[j]) 
  
  fdom_nnetar(forecast_date = forecast_date[j], targets_df = targets_df, var = var, 
              forecast_horizon = forecast_horizon, output_folder = output_folder)
  
      } #end for loop


```





