---
title: "fDOM Rain Lag regression forecasts"
author: "Dexter Howard"
date: "2024-08-27"
output: html_document
---


## Load packages and functions 

```{r}
library(tidyverse)

source('./Functions/RainLag_4cast_function.R')

```


## Get data 

target data 
```{r}
### S3 links 
targets_url <- "https://renc.osn.xsede.org/bio230121-bucket01/vera4cast/targets/project_id=vera4cast/duration=P1D/daily-insitu-targets.csv.gz"

### FCR water Q data
fcr_waterQ <- readr::read_csv(targets_url, show_col_types = FALSE) |>
  filter(site_id == "fcre",
         depth_m == 1.6,
         variable %in% c("fDOM_QSU_mean"))

###BVR water Q data
bvr_waterQ <- readr::read_csv(targets_url, show_col_types = FALSE) |>
  filter(site_id == "bvre",
         depth_m == 1.5,
         variable %in% c("fDOM_QSU_mean"))


### CCR water Q data
ccr_L1 <- read_csv("https://raw.githubusercontent.com/FLARE-forecast/CCRE-data/ccre-dam-data-qaqc/ccre-waterquality_L1.csv")
ccr_edi <- read_csv("https://pasta.lternet.edu/package/data/eml/edi/1069/2/ea78dd541e089687af1f4c4b550bc9ca" )
ccrfull <- rbind(ccr_edi, ccr_L1)

ccr_waterQ <- ccrfull |> 
  mutate(Date = as.Date(DateTime)) |> 
  group_by(Date) |> 
  summarise(fDOM_QSU_mean = mean(EXOfDOM_QSU_1, na.rm = T)) |> 
  mutate(site_id = "ccre",
         depth_m = 1.5) |> 
  select(Date, site_id, depth_m, fDOM_QSU_mean) |> 
  pivot_longer(-c(1:3), names_to = "variable", values_to = "observation") |> 
  rename(datetime = Date)

#remove uneeded data after loading 
rm(ccr_L1, ccr_edi, ccrfull, targets_url)


```


NOAA forecasts 
```{r}
## FCR and BVR 
fcr_bvr_noaa_daily <- read.csv("../Data/GeneratedData/FCR_NOAA_stage2_dailyaverage_27sep20-12aug24.csv")

## CCR
ccr_noaa_daily <- read.csv("../Data/GeneratedData/CCR_NOAA_stage2_dailyaverage_29sep20-12aug24.csv")

```


Set up directories to hold forecasts

```{r}
##uncomment if folders don't exist
# dir.create("../Data/RainLag_4casts")
# dir.create("../Data/RainLag_4casts/fcre")
# dir.create("../Data/RainLag_4casts/bvre")
# dir.create("../Data/RainLag_4casts/ccre")

```




## Run Rain Lag forecasts 

FCR
```{r}
##set up function inputs
#start forecasts at 12dec22 to line up w/ other forecasts
forecast_date <- seq(ymd("2022-12-12"), ymd("2024-08-11"), by = "day")

model_id <- "fDOM_RainLag_dwh"
var <- "fDOM_QSU_mean"
site <- "fcre"
forecast_depths <- 1.6
project_id <- "vera4cast"
n_members <- 31
forecast_horizon <- 16

calibration_start_date <- ymd("2020-09-27") #going back to start of noaa4casts since we're not limited by FLARE output

targets_df <- fcr_waterQ
noaa_4cast <- fcr_bvr_noaa_daily

output_folder <- paste0((str_sub(getwd(), end = -8)), "Data/RainLag_4casts/fcre/", model_id, "_", site, "_")


#run forecasts

for(j in 1:length(forecast_date)) {
  
  print(forecast_date[j]) 
  
  generate_fDOM_RainLag_forecast(forecast_date = forecast_date[j], forecast_horizon = forecast_horizon, 
                               n_members = n_members, output_folder = output_folder, model_id = model_id, 
                               targets_df = targets_df,
                       noaa_4cast = noaa_4cast, var = var,site = site, forecast_depths = forecast_depths,
                       project_id = project_id,
                      calibration_start_date = calibration_start_date )

      } #end function


## Notes on for loop: breaks 12aug24 - end of NOAA data


```



BVR
```{r}
##set up function inputs
#start forecasts at 12dec22 to line up w/ other forecasts
forecast_date <- seq(ymd("2022-12-12"), ymd("2024-08-11"), by = "day")

model_id <- "fDOM_RainLag_dwh"
var <- "fDOM_QSU_mean"
site <- "bvre"
forecast_depths <- 1.5
project_id <- "vera4cast"
n_members <- 31
forecast_horizon <- 16

calibration_start_date <- ymd("2020-09-27") #going back to start of noaa4casts since we're not limited by FLARE output

targets_df <- bvr_waterQ
noaa_4cast <- fcr_bvr_noaa_daily

output_folder <- paste0((str_sub(getwd(), end = -8)), "Data/RainLag_4casts/bvre/", model_id, "_", site, "_")


#run forecasts

for (j in 1:length(forecast_date)) {
  
  print(forecast_date[j]) 
  
generate_fDOM_RainLag_forecast(forecast_date = forecast_date[j], forecast_horizon = forecast_horizon, 
                               n_members = n_members, output_folder = output_folder, model_id = model_id, 
                               targets_df = targets_df,
                       noaa_4cast = noaa_4cast, var = var,site = site, forecast_depths = forecast_depths,
                       project_id = project_id,
                      calibration_start_date = calibration_start_date )

      } #end function


## Notes on for loop: breaks 12aug24 - end of NOAA data


```


CCR
```{r}
##set up function inputs
#start forecasts at 12dec22 to line up w/ other forecasts
forecast_date <- seq(ymd("2022-12-12"), ymd("2024-08-11"), by = "day")

model_id <- "fDOM_RainLag_dwh"
var <- "fDOM_QSU_mean"
site <- "ccre"
forecast_depths <- 1.5
project_id <- "vera4cast"
n_members <- 31
forecast_horizon <- 16

calibration_start_date <- ymd("2020-09-27") #going back to start of noaa4casts since we're not limited by FLARE output

targets_df <- ccr_waterQ
noaa_4cast <- ccr_noaa_daily

output_folder <- paste0((str_sub(getwd(), end = -8)), "Data/RainLag_4casts/ccre/", model_id, "_", site, "_")


#run forecasts

for (j in 1:length(forecast_date)) {
  
  print(forecast_date[j]) 
  
generate_fDOM_RainLag_forecast(forecast_date = forecast_date[j], forecast_horizon = forecast_horizon, 
                               n_members = n_members, output_folder = output_folder, model_id = model_id, 
                               targets_df = targets_df,
                       noaa_4cast = noaa_4cast, var = var,site = site, forecast_depths = forecast_depths,
                       project_id = project_id,
                      calibration_start_date = calibration_start_date )

      } #end function


## Notes on for loop: breaks 12aug24 - end of NOAA data


```







