---
title: "fDOM_Persistence_forecast_generation"
author: "Dexter Howard"
date: "2024-06-28"
output: html_document
---


## Load packages and functions 

```{r}
library(tidyverse)

source('./Functions/Persistence_4cast_function.R')

```


## Get data 

target data 
```{r}
### S3 links 
targets_url <- "https://renc.osn.xsede.org/bio230121-bucket01/vera4cast/targets/project_id=vera4cast/duration=P1D/daily-insitu-targets.csv.gz"

### FCR water Q data
fcr_waterQ <- readr::read_csv(targets_url, show_col_types = FALSE) |>
  filter(site_id == "fcre",
         depth_m == 1.6,
         variable %in% c("fDOM_QSU_mean"))

###BVR water Q data
bvr_waterQ <- readr::read_csv(targets_url, show_col_types = FALSE) |>
  filter(site_id == "bvre",
         depth_m == 1.5,
         variable %in% c("fDOM_QSU_mean"))


### CCR water Q data
ccr_L1 <- read_csv("https://raw.githubusercontent.com/FLARE-forecast/CCRE-data/ccre-dam-data-qaqc/ccre-waterquality_L1.csv")
ccr_edi <- read_csv("https://pasta.lternet.edu/package/data/eml/edi/1069/2/ea78dd541e089687af1f4c4b550bc9ca" )
ccrfull <- rbind(ccr_edi, ccr_L1)

ccr_waterQ <- ccrfull |> 
  mutate(Date = as.Date(DateTime)) |> 
  group_by(Date) |> 
  summarise(fDOM_QSU_mean = mean(EXOfDOM_QSU_1, na.rm = T)) |> 
  mutate(site_id = "ccre",
         depth_m = 1.5) |> 
  select(Date, site_id, depth_m, fDOM_QSU_mean) |> 
  pivot_longer(-c(1:3), names_to = "variable", values_to = "observation") |> 
  rename(datetime = Date) |> 
  mutate(duration = "P1D", project_id = "vera4cast")


#remove unneeded variables after loading
rm(ccr_edi, ccr_L1, ccrfull, targets_url)

```


Set up directories to hold forecasts

```{r}
##uncomment if folders don't exist locally
# dir.create("../Data/Persist_4casts")
# dir.create("../Data/Persist_4casts/fcre")
# dir.create("../Data/Persist_4casts/bvre")
# dir.create("../Data/Persist_4casts/ccre")

```


## Run Climatology forecasts for all reservoirs

FCR
```{r}
## set up dates for for loop
#start at 12dec22, so we have a month of calibration for first forecast and go to end of data set 
forecast_date <- seq(ymd("2022-12-12"), ymd("2024-08-11"), by = "day")

##set up inputs to function
model_id <- "fable_persistence"
var <- "fDOM_QSU_mean"
site <- "fcre"
depth <- 1.6
h <- 17

targets_df <- fcr_waterQ

output_folder <- paste0((str_sub(getwd(), end = -8)), "Data/Persist_4casts/fcre/", model_id, "_", site, "_")


#### FCR forecast loop

for (j in 1:length(forecast_date)) {
  
  print(forecast_date[j]) 
  
  generate_baseline_persistenceRW(targets = targets_df, site = site, var = var, 
                                  forecast_date = forecast_date[j], model_id = model_id, 
                                  h = h, depth = depth, bootstrap = F, 
                                  output_folder = output_folder)
              } #end loop

## NOTES

```



BVR

```{r}
## set up dates for for loop
#start at 12dec22, so we have a month of calibration for first forecast and go to end of data set 
forecast_date <- seq(ymd("2022-12-12"), ymd("2024-08-11"), by = "day")

##set up inputs to function
model_id <- "fable_persistence"
var <- "fDOM_QSU_mean"
site <- "bvre"
depth <- 1.5
h <- 17

targets_df <- bvr_waterQ

output_folder <- paste0((str_sub(getwd(), end = -8)), "Data/Persist_4casts/bvre/", model_id, "_", site, "_")


#### BVR forecast loop

for (j in 1:length(forecast_date)) {
  
  print(forecast_date[j]) 
  
  generate_baseline_persistenceRW(targets = targets_df, site = site, var = var, 
                                  forecast_date = forecast_date[j], model_id = model_id, 
                                  h = h, depth = depth, bootstrap = F, 
                                  output_folder = output_folder)
              } #end loop

## NOTES

```




CCR

```{r}
## set up dates for for loop
#start at 12dec22, so we have a month of calibration for first forecast and go to end of data set 
forecast_date <- seq(ymd("2022-12-12"), ymd("2024-08-11"), by = "day")

##set up inputs to function
model_id <- "fable_persistence"
var <- "fDOM_QSU_mean"
site <- "ccre"
depth <- 1.5
h <- 17

targets_df <- ccr_waterQ

output_folder <- paste0((str_sub(getwd(), end = -8)), "Data/Persist_4casts/ccre/", model_id, "_", site, "_")


#### CCR forecast loop

for (j in 1:length(forecast_date)) {
  
  print(forecast_date[j]) 
  
  generate_baseline_persistenceRW(targets = targets_df, site = site, var = var, 
                                  forecast_date = forecast_date[j], model_id = model_id, 
                                  h = h, depth = depth, bootstrap = F, 
                                  output_folder = output_folder)
              } #end loop

## NOTES

```







